export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const hostname = url.hostname;

    // Only process requests to arxivmd.org
    if (hostname !== "arxivmd.org") {
      return new Response("This service only works on arxivmd.org", {
        status: 400,
      });
    }

    // Extract the path from the URL
    const path = url.pathname;

    // Regular expression to match arXiv identifiers in the path
    // Match paths like /abs/2505.11821v1, /pdf/2505.11821, etc.
    const arxivPathRegex = /^\/(abs|pdf|src|html)\/([0-9]+\.[0-9]+v?[0-9]*)$/;
    const match = path.match(arxivPathRegex);

    if (!match) {
      return new Response(
        "Invalid arXiv URL format. Use arxivmd.org/abs/XXXX.XXXXXvX",
        {
          status: 400,
          headers: { "Content-Type": "text/plain" },
        },
      );
    }

    const [, pathType, identifier] = match;

    // Construct the URL to fetch the HTML version of the paper
    const arxivHtmlUrl = `https://arxiv.org/html/${identifier}`;

    try {
      // Use the reader.llmtext.com service as mentioned in the tweet
      const readerUrl = `https://reader.llmtext.com/md/arxiv.org/html/${identifier}`;

      // Fetch the markdown content
      const response = await fetch(readerUrl);

      if (!response.ok) {
        throw new Error(`Failed to fetch markdown: ${response.status}`);
      }

      const markdown = await response.text();

      // Add a header with information about the paper and links
      const headerMarkdown = `# arXiv Paper: ${identifier}
  
  > This is a Markdown version of [arXiv:${identifier}](https://arxiv.org/abs/${identifier})
  > 
  > [Original PDF](https://arxiv.org/pdf/${identifier}) | [Original HTML](https://arxiv.org/html/${identifier})
  >
  > Generated by [arxivmd.org](http://arxivmd.org)
  
  ---
  
  `;

      // Return the markdown with proper headers
      return new Response(headerMarkdown + markdown, {
        headers: {
          "Content-Type": "text/markdown; charset=UTF-8",
          "Access-Control-Allow-Origin": "*",
        },
      });
    } catch (error) {
      return new Response(`Error processing arXiv paper: ${error.message}`, {
        status: 500,
        headers: { "Content-Type": "text/plain" },
      });
    }
  },
};
